### ISSUE TITLE
Investigar retorno da criação de batalha (POST /battle)

### ISSUE THREAD

**Issue by thi4go** [thi4go/api_batalha_app#7]
Ao enviar um request com x usuarios, as vezes a api retorna uma batalha com uma stage, e um round dentro, com apenas três usuarios selecionados.

Pode ser pelo número de usuario, ou cálculo no numero de stage, algo assim

**Comment by daniangelos** [comment]
I'm on it

**Comment by thi4go** [comment]
Hahahahahah arroche
